Please add our magento wrapper for intro.js
usablica/introjs-website pull request #163
Opened 2022-08-17 13:56 UTC by socialresponse

Hi please add our magento wrapper

2022-08-19 08:46 UTC, afshinm requested changes

2022-08-19 08:46 UTC, afshinm commented on docs/wrappers/Magento.md
> +) - This module provides support for Intro.js on Magento-based websites. Created by [Rixxo](https://www.rixxo.com).
```suggestion
[Intro.js Magento](https://bitbucket.org/rxmodules-development/rixxo-introjs) - This module provides support for Intro.js on Magento-based websites.
```

2022-08-19 09:05 UTC, socialresponse commented
Changes have been committed

2022-09-06 15:24 UTC, socialresponse commented
@afshinm Hi Afshinm, could you approve this please,
thank you

2022-09-06 19:34 UTC, merged